name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up PHP environment (for Laravel)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, intl, bcmath, curl, zip, mysql

      # Step 4: Install dependencies with Composer
      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Step 5: Set up environment file
      - name: Set up .env file
        run: |
          cp .env.example .env
          php artisan key:generate
        env:
          APP_ENV: production
          APP_DEBUG: false
          APP_URL: ${{ secrets.APP_URL }} # or set your production URL

      # Step 6: Run Laravel optimizations
      - name: Run Laravel Optimizations
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Step 7: Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /Backend/

